Create quiz
ubclaunchpad/soil-topARgraphy pull request #24
Opened 2018-11-09 00:49 UTC by SophieMBerger

Changed from quiz to survey functionality.

2018-11-10 18:16 UTC, daphliu-zz requested changes
Code looks good!

Please delete the `/.idea/` & `/editor/app/.idea` folder and contents (**not** `/editor/.idea/`). Make sure you open up the editor folder in Android Studio, not any other folder.
Also delete the duplicate gradle files in `/editor/app`:
- `/editor/app/gradle` folder
- `/editor/app/gradlew`
- `/editor/app/gradlew.bat`
- `/editor/app/local.properties`

2018-11-10 18:39 UTC, daphliu-zz requested changes
Make sure to pull from master and resolve the merge conflicts. (QuizPanel.kt doesn't exist anymore) and change some variable names, then you're good to go!

2018-11-10 18:39 UTC, daphliu commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/ui/quizpanel/QuizPanelFragment.java
> +    private String type;
Change name for clarity. I think here you mean a "question"?

2018-11-10 18:39 UTC, daphliu commented on editor/app/src/main/res/layout/quiz_panel_fragment.xml
> +        android:id="@+id/caEditText"
Change the names here to answer1, answer2...

2018-11-10 18:39 UTC, daphliu commented on editor/app/src/main/res/layout/quiz_panel_fragment.xml
>  <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Use ConstraintLayout here instead of FrameLayout.

2018-11-10 18:39 UTC, daphliu commented on editor/app/src/main/res/layout/quiz_panel_fragment.xml
>  <?xml version="1.0" encoding="utf-8"?>
Check out the Design mode to see how it looks. Currently, your views are stacked on top of one another.

2018-11-11 08:10 UTC, daphliu-zz reviewed
Left a few more comments, mostly on naming conventions. The layout looks wonderful btw!!  We're keeping the json style in this PR just because it's only one file or else we'll have to duplicate branch, revert old branch to previous commit, then rebase new branch... etc. so let's not do that.. Create a new branch for json conversion after this PR is merged and use all lower case for naming :)

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/JsonUtil.java
> +        return null;
You probably meant to return `jsInfoPanel` 😄

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/JsonUtil.java
> +    public static String InfoToJSon (InfoPanel infoPanel){
Make sure to use consistent capitalization, so don't capitalize the `S` in JSON but not `on`.
Maybe change this to `infoToJson`?

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/JsonUtil.java
> +    public static String QuizToJSon (QuizPanel questionnaire){
`quizToJson`

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/JsonUtil.java
> +        return null;
`return jsInfoPanel`

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/res/layout/quiz_panel_fragment.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
Use ConstraintLayout not RelativeLayout

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/ui/quizpanel/QuizPanelFragment.java
> +    private String type;
I realized it's not a question but the title at the top. Can you rename it to soilType?

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/java/ca/ubc/eml/soiltopargraphy/editor/ui/quizpanel/QuizPanelFragment.java
> +                    case R.id.SoilTypeAnswerTv:
I think just SoilTypeAnswer is find here, not sure what Tv means :o

2018-11-11 08:10 UTC, daphliu-zz commented on editor/app/src/main/res/values/strings.xml
> +    <string name="soil_1">Soil 1</string>
I can't find where you've used these strings..

2018-11-12 04:22 UTC, SophieMBerger commented on editor/app/src/main/res/values/strings.xml
> +    <string name="soil_1">Soil 1</string>
In quiz_panel_fragment.xml

2018-11-12 04:23 UTC, SophieMBerger commented on editor/app/src/main/res/values/strings.xml
> +    <string name="soil_1">Soil 1</string>
It comes up when you check the usages of the strign when rightclicking on it

2018-11-18 23:48 UTC, closed without merging